.TH a2j 1 "August 2010" Linux "User Manuals"

.SH NAME
a2j \- Wrapper script to simulate a2jmidid's non-DBUS behaviour though a2jmidid actually being in DBUS mode
.SH SYNOPSIS
.B a2j [OPTIONS]
.SH OPTIONS
.IP -e
Also export MIDI hardware ports, not only software.
.SH AUTHOR
Eric Hedekar <after the beep at g mail dot nospam com>
.SH "SEE ALSO"
.BR a2jmidid (1),
.BR a2j_control (1),
.BR a2jmidi_bridge (1),
.BR j2amidi_bridge (1)

